"""One-time setup helper: copy the platform-specific pymd-plugin launcher
generated by `uv sync` (via the `[project.scripts]` console_scripts entry
point) to a single fixed-name path, so `myst.yml` can reference one literal
path that works unchanged on Windows, Linux, and Mac.

Why this is needed: `uv sync` / pip generate a *real* native launcher for a
console_scripts entry point, but its name and location differ by platform:
    Windows:      .venv/Scripts/pymd-plugin.exe
    Linux/Mac:    .venv/bin/pymd-plugin

mystmd's executable-plugin loader resolves the configured `path` with a
literal `fs.existsSync` check (no PATH search, no per-OS fallback), so
`myst.yml` can only ever contain one literal string. Copying whichever
platform's launcher exists to one fixed name lets that literal string be
identical on every OS.

The fixed name keeps a `.exe` suffix on *every* platform, not just Windows.
This isn't cosmetic: empirically, Node's `child_process.spawn()` (which is
what mystmd uses, without `shell: true`) refuses to spawn an extensionless
file directly on Windows -- it fails with ENOENT even though the file is a
valid PE executable and can be run directly from a shell (`./foo` works,
`spawn("foo")` does not). Appending `.exe` fixes that. On Linux/Mac this
suffix is inert: POSIX exec() and Node's spawn() there decide executability
from the file's permission bits and contents (ELF header / shebang), never
its name, so a `.exe`-suffixed ELF binary runs exactly the same as one
without the suffix.

Run this once after `uv sync` (or any time the launcher is regenerated):

    uv run python scripts/link_plugin_launcher.py
"""

import shutil
import stat
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
VENV_DIR = REPO_ROOT / ".venv"
FIXED_NAME = "pymd-plugin-bin.exe"


def _find_real_launcher() -> Path:
    candidates = [
        VENV_DIR / "Scripts" / "pymd-plugin.exe",  # Windows
        VENV_DIR / "bin" / "pymd-plugin",  # Linux/Mac
    ]
    for candidate in candidates:
        if candidate.exists():
            return candidate
    raise SystemExit(
        "link_plugin_launcher: could not find a generated pymd-plugin launcher "
        f"in any of: {[str(c) for c in candidates]}. Run `uv sync` first."
    )


def main():
    source = _find_real_launcher()
    dest = VENV_DIR / FIXED_NAME

    shutil.copyfile(source, dest)

    # Preserve/ensure the executable bit on POSIX (copyfile does not copy
    # permissions; Windows ignores chmod bits so this is a no-op there).
    if sys.platform != "win32":
        mode = source.stat().st_mode
        dest.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    print(f"Copied {source} -> {dest}")


if __name__ == "__main__":
    main()
